In [1]:
# Quick NumPy Tutorial (Google Colab Ready)

import numpy as np

# --- 1. Creating Arrays ---
print("1D Array:", np.array([1, 2, 3, 4]))
print("2D Array:\n", np.array([[1, 2], [3, 4]]))
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((3, 3)))
print("Random:\n", np.random.rand(2, 2))

# --- 2. Properties ---
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Dimensions of b:", b.ndim)

# --- 3. Indexing & Slicing ---
print("First element of a:", a[0])
print("Element at row1,col1 in b:", b[1,1])
print("Slice a[1:3]:", a[1:3])

# --- 4. Math Operations ---
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print("x+y:", x+y)
print("x*y:", x*y)
print("x squared:", x**2)

# --- 5. Useful Functions ---
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Std Dev:", np.std(arr))

# --- 6. Matrix Operations ---
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix Multiplication:\n", A @ B)
print("Inverse of A:\n", np.linalg.inv(A))

# --- 7. Random Numbers ---
print("Random integers:", np.random.randint(1, 10, size=5))
print("Random normal:", np.random.normal(0, 1, size=5))

# --- Exercises ---
# 1. Create a 1D array of numbers 1 to 10 and print only even numbers
# 2. Generate a 3x3 random matrix and find its determinant
# 3. Create two arrays and compute cosine similarity
# 4. Normalize an array (values between 0 and 1)


1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.27717881 0.60296578]
 [0.70253036 0.9547137 ]]
Shape of a: (4,)
Shape of b: (2, 2)
Dimensions of b: 2
First element of a: 1
Element at row1,col1 in b: 4
Slice a[1:3]: [2 3]
x+y: [11 22 33]
x*y: [10 40 90]
x squared: [1 4 9]
Mean: 3.0
Sum: 15
Max: 5
Std Dev: 1.4142135623730951
Matrix Multiplication:
 [[19 22]
 [43 50]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Random integers: [6 5 7 6 9]
Random normal: [-0.94111623 -1.5553991   0.65372996 -2.56900687 -1.78542705]
